#!/bin/bash
#
#%# family=auto
#%# capabilities=autoconf

if [ -z $MUNIN_LIBDIR ]; then
    MUNIN_LIBDIR=/usr/share/munin
fi

. $MUNIN_LIBDIR/plugins/kyototycoon_plugin.sh

if [ -z $kthost ]; then
    kthost=$KTHOST
fi
if [ -z $ktport ]; then
    ktport=$KTPORT
fi
if [ -z $ktdb ]; then
    ktdb=$KTDB
fi

# setup graph vars
name=$(basename $0 | cut -d_ -f1)

case $1 in
config)
    cat <<EOF
graph_title ${name}: rpc commands
graph_category kyoto
graph_args --base 1024
graph_info rpc commands
EOF

    ktreport | grep -E "^cnt_" | cut -d: -f1 | cut -d_ -f2- | while read field; do
        echo "${field}.label ${field}"
        echo "${field}.draw AREA"
        echo "${field}.type DERIVE"
    done
    exit 0
    ;;

autoconf)
    if [ "$(pgrep ktserver)" == "" ]; then
        echo no
    else
        echo yes
    fi
    exit 0
    ;;
esac

ktreport | grep -E "^cnt_" | while read line; do
   echo $line | sed -e "s/^cnt_\(.*\):\s\+\([0-9]\+\)$/\1.value \2/"
done
